### ISSUE TITLE
Consider renaming {Operation}By to Ordered{Operation}

### ISSUE THREAD

**Issue by marcelocantos** [arr-ai/frozen#10]
E.g., `RangeBy` should perhaps be called `OrderedRange` instead. Same goes for other operations that takes a `less` parameter.

Actually, `FirstBy` and `FirstNBy` should probably just be called `First` and `FirstN` because the ordering aspect is captured in the term `First`.

**Comment by nofun97** [comment]
`RangeBy` looks more readable to me. There's already `Range` that returns an iterator with no order so it implies that `RangeBy` is in a defined order and besides it is shorter. Are there strong reasons to change it to `OrderedRange`?

**Comment by marcelocantos** [comment]
One issue driving this is that there is also `GroupBy`, which doesn't imply ordering. `OrderedRange` is more verbose, which is a slight negative, but it is definitely clearer in its intent.

It's not a big issue, and there's merit on both side of this, so I'm happy to go either way. It's your call, @nofun97.
