### ISSUE TITLE
Implement (Set).OrderedRangeN

### ISSUE THREAD

**Issue by marcelocantos** [arr-ai/frozen#12]
```go
func (s Set) OrderedRangeN(less func(a, b interface{}) bool) Iterator
```

Iterates over the first _n_ elements per the given ordering. Doing this efficiently will require changing `s.root.orderedIterator` to `s.root.orderedIteratorN`, which bounds the size of the internal heap. To support the current unbounded behaviour, replace n = -1 with n = max-int.

**Comment by nofun97** [comment]
as discussed, replaced to 
```go
func (s Set) OrderedFirstN(n int, less func(a, b interface{}) bool) []interface{}
```
