### ISSUE TITLE
Implement NewSetFromStrings

### ISSUE THREAD

**Issue by marcelocantos** [arr-ai/frozen#29]
```go
func NewSetFromStrings(s ...string) Set
```

String sets are very common, given their close relationship to maps with string keys, which are also very common.

**Comment by nofun97** [comment]
isn't this just `NewSet` with all string arguments?

**Comment by nofun97** [comment]
ok got it, it doesn't work `NewSet(s...)` doesn't work because casting from `[]string` to `[]interface{}` is not possible
